// <auto-generated>
//  automatically @generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ovrAvatar.Arbiter
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public enum ProtocolVersion : int
{
  Major = 0,
  Minor = 1,
};

public enum Packet : byte
{
  NONE = 0,
  SessionPacket = 1,
  TestPacket = 2,
  PropertyPacket = 3,
  AvatarSDKEventPacket = 4,
  NetworkStatsPacket = 5,
  MemoryStatsPacket = 6,
  TaskStatsPacket = 7,
};

public class PacketUnion {
  public Packet Type { get; set; }
  public object Value { get; set; }

  public PacketUnion() {
    this.Type = Packet.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public ovrAvatar.Arbiter.SessionPacketT AsSessionPacket() { return this.As<ovrAvatar.Arbiter.SessionPacketT>(); }
  public ovrAvatar.Arbiter.TestPacketT AsTestPacket() { return this.As<ovrAvatar.Arbiter.TestPacketT>(); }
  public ovrAvatar.Arbiter.PropertyPacketT AsPropertyPacket() { return this.As<ovrAvatar.Arbiter.PropertyPacketT>(); }
  public ovrAvatar.Arbiter.AvatarSDKEventPacketT AsAvatarSDKEventPacket() { return this.As<ovrAvatar.Arbiter.AvatarSDKEventPacketT>(); }
  public ovrAvatar.Arbiter.NetworkStatsPacketT AsNetworkStatsPacket() { return this.As<ovrAvatar.Arbiter.NetworkStatsPacketT>(); }
  public ovrAvatar.Arbiter.MemoryStatsPacketT AsMemoryStatsPacket() { return this.As<ovrAvatar.Arbiter.MemoryStatsPacketT>(); }
  public ovrAvatar.Arbiter.TaskStatsPacketT AsTaskStatsPacket() { return this.As<ovrAvatar.Arbiter.TaskStatsPacketT>(); }

  public static int Pack(FlatBuffers.FlatBufferBuilder builder, PacketUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case Packet.SessionPacket: return ovrAvatar.Arbiter.SessionPacket.Pack(builder, _o.AsSessionPacket()).Value;
      case Packet.TestPacket: return ovrAvatar.Arbiter.TestPacket.Pack(builder, _o.AsTestPacket()).Value;
      case Packet.PropertyPacket: return ovrAvatar.Arbiter.PropertyPacket.Pack(builder, _o.AsPropertyPacket()).Value;
      case Packet.AvatarSDKEventPacket: return ovrAvatar.Arbiter.AvatarSDKEventPacket.Pack(builder, _o.AsAvatarSDKEventPacket()).Value;
      case Packet.NetworkStatsPacket: return ovrAvatar.Arbiter.NetworkStatsPacket.Pack(builder, _o.AsNetworkStatsPacket()).Value;
      case Packet.MemoryStatsPacket: return ovrAvatar.Arbiter.MemoryStatsPacket.Pack(builder, _o.AsMemoryStatsPacket()).Value;
      case Packet.TaskStatsPacket: return ovrAvatar.Arbiter.TaskStatsPacket.Pack(builder, _o.AsTaskStatsPacket()).Value;
    }
  }
}

public struct TestPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TestPacket GetRootAsTestPacket(ByteBuffer _bb) { return GetRootAsTestPacket(_bb, new TestPacket()); }
  public static TestPacket GetRootAsTestPacket(ByteBuffer _bb, TestPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TestPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TestValue { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool MutateTestValue(uint test_value) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, test_value); return true; } else { return false; } }

  public static Offset<ovrAvatar.Arbiter.TestPacket> CreateTestPacket(FlatBufferBuilder builder,
      uint test_value = 0) {
    builder.StartTable(1);
    TestPacket.AddTestValue(builder, test_value);
    return TestPacket.EndTestPacket(builder);
  }

  public static void StartTestPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTestValue(FlatBufferBuilder builder, uint testValue) { builder.AddUint(0, testValue, 0); }
  public static Offset<ovrAvatar.Arbiter.TestPacket> EndTestPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ovrAvatar.Arbiter.TestPacket>(o);
  }
  public TestPacketT UnPack() {
    var _o = new TestPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TestPacketT _o) {
    _o.TestValue = this.TestValue;
  }
  public static Offset<ovrAvatar.Arbiter.TestPacket> Pack(FlatBufferBuilder builder, TestPacketT _o) {
    if (_o == null) return default(Offset<ovrAvatar.Arbiter.TestPacket>);
    return CreateTestPacket(
      builder,
      _o.TestValue);
  }
};

public class TestPacketT
{
  public uint TestValue { get; set; }

  public TestPacketT() {
    this.TestValue = 0;
  }
}

public struct ArbiterPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ArbiterPacket GetRootAsArbiterPacket(ByteBuffer _bb) { return GetRootAsArbiterPacket(_bb, new ArbiterPacket()); }
  public static ArbiterPacket GetRootAsArbiterPacket(ByteBuffer _bb, ArbiterPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool ArbiterPacketBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "NRTC"); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArbiterPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint SessionId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool MutateSessionId(uint session_id) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutUint(o + __p.bb_pos, session_id); return true; } else { return false; } }
  public ulong Timestamp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public bool MutateTimestamp(ulong timestamp) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutUlong(o + __p.bb_pos, timestamp); return true; } else { return false; } }
  public ovrAvatar.Arbiter.Packet DataType { get { int o = __p.__offset(8); return o != 0 ? (ovrAvatar.Arbiter.Packet)__p.bb.Get(o + __p.bb_pos) : ovrAvatar.Arbiter.Packet.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(10); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public ovrAvatar.Arbiter.SessionPacket DataAsSessionPacket() { return Data<ovrAvatar.Arbiter.SessionPacket>().Value; }
  public ovrAvatar.Arbiter.TestPacket DataAsTestPacket() { return Data<ovrAvatar.Arbiter.TestPacket>().Value; }
  public ovrAvatar.Arbiter.PropertyPacket DataAsPropertyPacket() { return Data<ovrAvatar.Arbiter.PropertyPacket>().Value; }
  public ovrAvatar.Arbiter.AvatarSDKEventPacket DataAsAvatarSDKEventPacket() { return Data<ovrAvatar.Arbiter.AvatarSDKEventPacket>().Value; }
  public ovrAvatar.Arbiter.NetworkStatsPacket DataAsNetworkStatsPacket() { return Data<ovrAvatar.Arbiter.NetworkStatsPacket>().Value; }
  public ovrAvatar.Arbiter.MemoryStatsPacket DataAsMemoryStatsPacket() { return Data<ovrAvatar.Arbiter.MemoryStatsPacket>().Value; }
  public ovrAvatar.Arbiter.TaskStatsPacket DataAsTaskStatsPacket() { return Data<ovrAvatar.Arbiter.TaskStatsPacket>().Value; }

  public static Offset<ovrAvatar.Arbiter.ArbiterPacket> CreateArbiterPacket(FlatBufferBuilder builder,
      uint session_id = 0,
      ulong timestamp = 0,
      ovrAvatar.Arbiter.Packet data_type = ovrAvatar.Arbiter.Packet.NONE,
      int dataOffset = 0) {
    builder.StartTable(4);
    ArbiterPacket.AddTimestamp(builder, timestamp);
    ArbiterPacket.AddData(builder, dataOffset);
    ArbiterPacket.AddSessionId(builder, session_id);
    ArbiterPacket.AddDataType(builder, data_type);
    return ArbiterPacket.EndArbiterPacket(builder);
  }

  public static void StartArbiterPacket(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSessionId(FlatBufferBuilder builder, uint sessionId) { builder.AddUint(0, sessionId, 0); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(1, timestamp, 0); }
  public static void AddDataType(FlatBufferBuilder builder, ovrAvatar.Arbiter.Packet dataType) { builder.AddByte(2, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(3, dataOffset, 0); }
  public static Offset<ovrAvatar.Arbiter.ArbiterPacket> EndArbiterPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ovrAvatar.Arbiter.ArbiterPacket>(o);
  }
  public static void FinishArbiterPacketBuffer(FlatBufferBuilder builder, Offset<ovrAvatar.Arbiter.ArbiterPacket> offset) { builder.Finish(offset.Value, "NRTC"); }
  public static void FinishSizePrefixedArbiterPacketBuffer(FlatBufferBuilder builder, Offset<ovrAvatar.Arbiter.ArbiterPacket> offset) { builder.FinishSizePrefixed(offset.Value, "NRTC"); }
  public ArbiterPacketT UnPack() {
    var _o = new ArbiterPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ArbiterPacketT _o) {
    _o.SessionId = this.SessionId;
    _o.Timestamp = this.Timestamp;
    _o.Data = new ovrAvatar.Arbiter.PacketUnion();
    _o.Data.Type = this.DataType;
    switch (this.DataType) {
      default: break;
      case ovrAvatar.Arbiter.Packet.SessionPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.SessionPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.SessionPacket>().Value.UnPack() : null;
        break;
      case ovrAvatar.Arbiter.Packet.TestPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.TestPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.TestPacket>().Value.UnPack() : null;
        break;
      case ovrAvatar.Arbiter.Packet.PropertyPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.PropertyPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.PropertyPacket>().Value.UnPack() : null;
        break;
      case ovrAvatar.Arbiter.Packet.AvatarSDKEventPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.AvatarSDKEventPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.AvatarSDKEventPacket>().Value.UnPack() : null;
        break;
      case ovrAvatar.Arbiter.Packet.NetworkStatsPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.NetworkStatsPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.NetworkStatsPacket>().Value.UnPack() : null;
        break;
      case ovrAvatar.Arbiter.Packet.MemoryStatsPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.MemoryStatsPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.MemoryStatsPacket>().Value.UnPack() : null;
        break;
      case ovrAvatar.Arbiter.Packet.TaskStatsPacket:
        _o.Data.Value = this.Data<ovrAvatar.Arbiter.TaskStatsPacket>().HasValue ? this.Data<ovrAvatar.Arbiter.TaskStatsPacket>().Value.UnPack() : null;
        break;
    }
  }
  public static Offset<ovrAvatar.Arbiter.ArbiterPacket> Pack(FlatBufferBuilder builder, ArbiterPacketT _o) {
    if (_o == null) return default(Offset<ovrAvatar.Arbiter.ArbiterPacket>);
    var _data_type = _o.Data == null ? ovrAvatar.Arbiter.Packet.NONE : _o.Data.Type;
    var _data = _o.Data == null ? 0 : ovrAvatar.Arbiter.PacketUnion.Pack(builder, _o.Data);
    return CreateArbiterPacket(
      builder,
      _o.SessionId,
      _o.Timestamp,
      _data_type,
      _data);
  }
};

public class ArbiterPacketT
{
  public uint SessionId { get; set; }
  public ulong Timestamp { get; set; }
  public ovrAvatar.Arbiter.PacketUnion Data { get; set; }

  public ArbiterPacketT() {
    this.SessionId = 0;
    this.Timestamp = 0;
    this.Data = null;
  }
  public static ArbiterPacketT DeserializeFromBinary(byte[] fbBuffer) {
    return ArbiterPacket.GetRootAsArbiterPacket(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ArbiterPacket.FinishArbiterPacketBuffer(fbb, ArbiterPacket.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
