// <auto-generated>
//  automatically @generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ovrAvatar.Arbiter
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AvatarSDKEventPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static AvatarSDKEventPacket GetRootAsAvatarSDKEventPacket(ByteBuffer _bb) { return GetRootAsAvatarSDKEventPacket(_bb, new AvatarSDKEventPacket()); }
  public static AvatarSDKEventPacket GetRootAsAvatarSDKEventPacket(ByteBuffer _bb, AvatarSDKEventPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AvatarSDKEventPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<ovrAvatar.Arbiter.AvatarSDKEventPacket> CreateAvatarSDKEventPacket(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    AvatarSDKEventPacket.AddName(builder, nameOffset);
    return AvatarSDKEventPacket.EndAvatarSDKEventPacket(builder);
  }

  public static void StartAvatarSDKEventPacket(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<ovrAvatar.Arbiter.AvatarSDKEventPacket> EndAvatarSDKEventPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ovrAvatar.Arbiter.AvatarSDKEventPacket>(o);
  }
  public AvatarSDKEventPacketT UnPack() {
    var _o = new AvatarSDKEventPacketT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AvatarSDKEventPacketT _o) {
    _o.Name = this.Name;
  }
  public static Offset<ovrAvatar.Arbiter.AvatarSDKEventPacket> Pack(FlatBufferBuilder builder, AvatarSDKEventPacketT _o) {
    if (_o == null) return default(Offset<ovrAvatar.Arbiter.AvatarSDKEventPacket>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreateAvatarSDKEventPacket(
      builder,
      _name);
  }
};

public class AvatarSDKEventPacketT
{
  public string Name { get; set; }

  public AvatarSDKEventPacketT() {
    this.Name = null;
  }
}


}
