#ifndef OVR_AVATAR_MOTION_VECTORS_CORE_REFERENCE_INCLUDED
#define OVR_AVATAR_MOTION_VECTORS_CORE_REFERENCE_INCLUDED

#include "Packages/com.meta.xr.sdk.avatars/Scripts/ShaderUtils/OvrAvatarMotionVectorsCore.hlsl"

#endif // OVR_AVATAR_MOTION_VECTORS_CORE_REFERENCE_INCLUDED
